apiVersion: apps/v1
kind: Deployment
metadata:
  name: testwebapi-deployment
spec:
  selector:
    matchLabels:
      app: testwebapi-pod
  template:
    metadata:
      labels:
        app: testwebapi-pod
    spec:
      containers:
      - name: testwebapi-container
        image: testwebapi:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
