apiVersion: v1
kind: Service
metadata:
  name: testwebapi-service
spec:
  selector:
    app: testwebapi-pod
  ports:
  - port: 5000
    targetPort: 5000
  externalTrafficPolicy: Local
  type: LoadBalancer
